let scenes=[ 

            [   
                  {"sprite":"entryexit_entry","x":62,"y":-203}, 
                  {"sprite":"entryexit_exit","x":1128,"y":854},                           
                  {"sprite":"player","x":400,"y":300,"width":100,"height":100},  
                  {"sprite":"wall","x":-100,"y":300,"width":50,"height":1280,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},  
                  {"sprite":"wall","x":1275,"y":-26,"width":50,"height":1382,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},
                  {"sprite":"wall","x":663,"y":-341,"width":1608,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true}, 
                  {"sprite":"wall","x":375,"y":458,"width":1280,"height":50,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},  
                  {"sprite":"wall","x":563,"y":942,"width":1380,"height":50,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true}, 
                  {"sprite":"camstopper_left","x":312,"y":-200},
                  {"sprite":"camstopper_right","x":1012,"y":800},            
                  {"sprite":"scenechanger_scright","x":1350,"y":854},  
                  {"sprite":"flower","x":419,"y":241,"width":50,"height":50},    
                  {"sprite":"flower","x":669,"y":322,"width":50,"height":50},  
                  {"sprite":"flower","x":669,"y":-189,"width":50,"height":50},    
                  {"sprite":"flower","x":1019,"y":-189,"width":50,"height":50},  
                  {"sprite":"flower","x":907,"y":308,"width":50,"height":50},   
                  {"sprite":"flower","x":557,"y":308,"width":50,"height":50},
                  {"sprite":"flower","x":-6,"y":200,"width":50,"height":50}, 

            ],

            [  
                  {"sprite":"scenechanger_scleft","x":-300,"y":300},  
                  {"sprite":"scenechanger_scright","x":925,"y":586}, 
                  {"sprite":"entryexit_entry","x":-160,"y":300}, 
                  {"sprite":"entryexit_exit","x":762,"y":586}, 
                  {"sprite":"camstopper_left","x":100,"y":300},
                  {"sprite":"camstopper_right","x":587,"y":600},                            
                  // {"sprite":"player","x":400,"y":300,"width":100,"height":100},  
                  {"sprite":"wall","x":338,"y":156,"width":1000,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
                   {"sprite":"wall","x":338,"y":688,"width":1000,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true}, 
                   {"sprite":"wall","x":-174,"y":538,"width":50,"height":340,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},  
                   {"sprite":"wall","x":838,"y":347,"width":50,"height":340,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},
                   // {"sprite":"zombie","x":326,"y":395,"width":140 ,"height":140,
                   //  "offsetx":0,"offsety":0, "sprite_id":"zombie1"},  
                  {"sprite":"flower","x":126,"y":595,"width":50,"height":50}, 
                  {"sprite":"gate","x":-126,"y":500,"width":50,"height":200,"dirx":"up"},  
                  {"sprite":"gate","x":787,"y":340,"width":50,"height":200,"dirx":"down"},                     
            ],
            [  
                  {"sprite":"scenechanger_scleft","x":-300,"y":300},   
                  {"sprite":"scenechanger_scright","x":1450,"y":300},
                  {"sprite":"entryexit_entry","x":-50,"y":300}, 
                  {"sprite":"entryexit_exit","x":1363,"y":300}, 
                  {"sprite":"camstopper_left","x":76,"y":300},
                  {"sprite":"camstopper_right","x":987,"y":300},                            
                  // {"sprite":"player","x":400,"y":300,"width":100,"height":100},  
                  {"sprite":"wall","x":663,"y":156,"width":1608,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
                   {"sprite":"wall","x":663,"y":392,"width":1608,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true}, 

            ],
            [  
                  {"sprite":"scenechanger_scleft","x":-300,"y":300},  
                  {"sprite":"scenechanger_scright","x":1600,"y":322}, 
                  {"sprite":"entryexit_entry","x":-160,"y":300}, 
                  {"sprite":"entryexit_exit","x":1512,"y":349}, 
                  {"sprite":"camstopper_left","x":100,"y":300},
                  {"sprite":"camstopper_right","x":1337,"y":308},                            
                  // {"sprite":"player","x":400,"y":300,"width":100,"height":100},  
                  {"sprite":"wall","x":663,"y":156,"width":1764,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
                   {"sprite":"wall","x":663,"y":507,"width":1764,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true}, 
                   {"sprite":"wall","x":0,"y":410,"width":50,"height":190,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},  
                   {"sprite":"wall","x":838,"y":260,"width":50,"height":180,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},                    
                  {"sprite":"flower","x":313,"y":345,"width":50,"height":50}, 
                  {"sprite":"flower","x":500,"y":400,"width":50,"height":50}, 
                  {"sprite":"flower","x":700,"y":345,"width":50,"height":50}, 
                  {"sprite":"flower","x":1200,"y":345,"width":50,"height":50}, 
                                     
            ],
            [
              {"sprite":"scenechanger_scleft","x":-288,"y":300},    
              {"sprite":"entryexit_entry","x":0,"y":300},
              {"sprite":"wall","x":75,"y":439,"width":600,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
              {"sprite":"wall","x":75,"y":161,"width":600,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},              
              {"sprite":"wall","x":412,"y":605,"width":50,"height":368,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},
              {"sprite":"wall","x":412,"y":6,"width":50,"height":368,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},
              {"sprite":"wall","x":712,"y":-159,"width":653,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
              {"sprite":"wall","x":712,"y":759,"width":653,"height":52,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":true},
              {"sprite":"wall","x":1050,"y":200,"width":50,"height":670,
                   "hitboxoffsetx":0,"hitboxoffsety":0,"isHori":false},
              {"sprite":"camstopper_left","x":100,"y":0},
              {"sprite":"camstopper_right","x":1150,"y":608},
              {"sprite":"beetle","x":630,"y":286,"width":210 ,"height":280,
                  "offsetx":40,"offsety":-15, "sprite_id":"beetle1"},

            ],
           ];